name: 'Test-action'

on:
    push:
        branchs: [ main ]

jobs:
    test-build:
        name: 'Terraform'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
            uses: actions/checkout@v4
